import {STATIC_PAGES,FEEDBACK_URL,KURUMI_URL} from './deployment-config.js?v=82ac3ff11395dbeeecb02c3d06dcb66bd310dc05';
import {design,CATEGORIES,RARITIES,description,canUpgrade,cardPrice,effectSummary,comboFor,COMBOS} from './card-design.js?v=82ac3ff11395dbeeecb02c3d06dcb66bd310dc05';
import {TRADE_UPGRADABLE,TIMES,slots,units,price,equity,oldUnits,estimatedPnl} from './trading.js?v=82ac3ff11395dbeeecb02c3d06dcb66bd310dc05';
import {chartMarkup,animateCandles} from './market-chart.js?v=82ac3ff11395dbeeecb02c3d06dcb66bd310dc05';
import {Telemetry} from './telemetry.js?v=82ac3ff11395dbeeecb02c3d06dcb66bd310dc05';
import {showSettlement} from './settlement.js?v=82ac3ff11395dbeeecb02c3d06dcb66bd310dc05';
import {availablePosition,tradingRestriction} from './live-market.js?v=82ac3ff11395dbeeecb02c3d06dcb66bd310dc05';
import {GameAudio} from './audio.js?v=82ac3ff11395dbeeecb02c3d06dcb66bd310dc05';
import {GameMotion,ActionGate,feedback} from './feedback.js?v=82ac3ff11395dbeeecb02c3d06dcb66bd310dc05';
import {features,stage,marketFor,cardText,BUILDS,STAGES} from './progression.js?v=82ac3ff11395dbeeecb02c3d06dcb66bd310dc05';
import {CARDS,CARD,RELICS,RELIC,MARKETS,EVENTS,MOODS,NODE_LABELS,NODE_ICONS,STARTER} from './data.js?v=82ac3ff11395dbeeecb02c3d06dcb66bd310dc05';
import {createLiveRun,migrateRun,act,intent,cardCost,exposure,hotSector,validRun,UPGRADABLE} from './engine.js?v=82ac3ff11395dbeeecb02c3d06dcb66bd310dc05';
const $=s=>document.querySelector(s),root=$('#app');
const KEY='leek-spire-v1';let storageOK=true,cache={};try{cache=JSON.parse(localStorage.getItem(KEY)||'{}')||{};}catch{storageOK=false;}
let prefs={sound:true,music:false,soundVolume:.65,musicVolume:.22,motion:true,analytics:true,...cache.prefs,music:false},stats={best:100,wins:0,runs:0,unlocked:['probe','reduce'],...cache.stats};let saved=validRun(cache.run)?migrateRun(cache.run):null,run=null,modal=null,toastTimer,settling=false,advancing=false;
const money=n=>'¥'+Math.round(n*1000).toLocaleString('zh-CN');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function persist(){try{localStorage.setItem(KEY,JSON.stringify({prefs,stats,run:run||saved}));}catch{storageOK=false;}}
const audio=new GameAudio({onError:()=>notify('声音暂时未能加载，游戏可继续。可在设置里重新开启。')}),motion=new GameMotion(),gate=new ActionGate(),telemetry=new Telemetry(prefs.analytics);
function sound(kind='play'){audio.effect(kind);}
document.addEventListener('visibilitychange',()=>audio.sync());
window.addEventListener('pagehide',()=>audio.pause());
matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',()=>motion.configure(prefs.motion,prefs.motionMode==='full'));
function notify(t){let el=$('#toast');if(!el){el=document.createElement('div');el.id='toast';el.setAttribute('role','status');document.body.append(el);}el.textContent=t;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),3100);}
function dispatch(a,input='pointer'){
 const target=a.type==='play'?'card:'+(run?.combat?.hand[a.index]?.id||'unknown'):a.type;
 const exposure=a.type==='play'?`${run.runId}-${run.rounds+1}-${run.combat.hand[a.index]?.uid}`:'';
 if(a.type!=='tick')telemetry.action('action_attempt',target,{input,exposure});
 if(gate.busy||settling||advancing){if(a.type!=='tick')telemetry.action('action_rejected',target,{reason:'结算反馈中',input,exposure});return false;}
 try{
  const before=run,snapshot=motion.capture(a),next=act(run,a),f=feedback(run,next,a);
  gate.hold(a.type==='end'?500:a.type==='advance'?0:320);run=next;saved=run;
  for(const c of run.deck)if(!stats.unlocked.includes(c.id))stats.unlocked.push(c.id);
  stats.best=Math.max(stats.best,run.peak);
  if(run.screen==='result'&&before.screen!=='result'){stats.runs++;if(run.won)stats.wins++;telemetry.emit('run_end','',{detail:{success:run.won,amount:run.hp*1000}});}
  persist();

  telemetry.action('action_success',target,{input,exposure,amount:(run.hp-before.hp)*1000});
  modal=null;
  if(a.type==='end'){
   settling=true;
   showSettlement(run.lastSettlement,{audio,motion,onDone:()=>{settling=false;render();motion.enter();sound('draw');if(run.combat?.triggers?.length){audio.effect('power',{rate:1.15,level:.5});motion.animate($('.effects-panel'),[{filter:'brightness(1.6)'},{filter:'brightness(1)'}],{duration:800});}window.scrollTo({top:0,behavior:'instant'});},onSkip:()=>telemetry.emit('settlement_skip')});return true;
  }
  render();
  if(a.type==='advance'){advancing=true;if(innerWidth<1000)$('[data-live-panel]')?.scrollIntoView({behavior:'instant',block:'start'});root.classList.add('advancing');root.querySelectorAll('[data-action]').forEach(b=>b.disabled=true);const status=$('[data-time-status]');if(status)status.textContent='行情回放中…';animateCandles(root,before.combat.live.step,motion.enabled).finally(()=>{advancing=false;root.classList.remove('advancing');render();});return true;}
  if(run.screen!==before.screen||f.unlocked)window.scrollTo({top:0,behavior:'instant'});
  if(a.type==='play'){audio.effect('rattle',{rate:.85,level:.35});if(f.tone!=='play')sound('play');}sound(f.tone);motion.present(before,run,a,snapshot,f);if(a.type==='upgrade'){audio.effect('upgrade',{rate:1.2});notify('强化完成，卡牌已更新。');}if(a.type==='play'){const played=before.combat.hand[a.index],meta=design(played.id);if(['power','yield'].includes(meta.key)){audio.effect(meta.key==='power'?'power':'dividend',{rate:meta.rarity==='rare'?1.2:1});motion.animate($('.effects-panel'),[{opacity:.35,transform:'translateY(10px)'},{opacity:1,transform:'none'}],{duration:550});}if(meta.exhaust)audio.effect('exhaust',{level:.35});}
  if(['buy','remove','tool','bet'].includes(a.type))notify(run.notice);
  return true;
 }catch(e){if(a.type!=='tick')telemetry.action('action_rejected',target,{reason:e.message,input,exposure});notify(e.message);return false;}
}
function start(){run=createLiveRun();advancing=false;saved=run;persist();render();telemetry.emit('run_start');window.scrollTo({top:0,behavior:'instant'});motion.clear();motion.enter();sound('draw');}
function header(){return `<header class="topbar"><a class="brand" href="./" aria-label="韭菜尖塔首页"><span class="logo">韭</span>韭菜尖塔 <small>LEEK SPIRE</small></a><div class="nav"><span class="terminal-tag">${run?'散户 001 / 第一轮牛熊':'散户生存终端 / 手动交易版'}</span>${run&&features(run).full?'<button data-ui="codex" class="nav-btn">卡牌图鉴</button><button data-ui="help" class="nav-btn">交易指南</button>':''}<button data-ui="mute" class="icon-btn audio-toggle" aria-label="${prefs.sound?'静音':'开启声音'}" aria-pressed="${!prefs.sound}" title="${prefs.sound?'声音已开启':'声音已关闭'}">${prefs.sound?'♫':'♪'}</button>${STATIC_PAGES?`<a class="nav-btn" data-feedback-link href="${FEEDBACK_URL}" target="_blank" rel="noopener noreferrer">留言 ↗</a>`:'<button data-ui="feedback" class="nav-btn">留言</button>'}<a class="nav-btn" data-game-link href="${KURUMI_URL}" target="_blank" rel="noopener noreferrer">久留美 ↗</a><button data-ui="settings" class="icon-btn" aria-label="设置与音效">⚙</button></div></header>`;}
function candles(hero=false){let tape=!hero&&run?.combat?.tape;let count=tape?tape.length:32,values=[],v=50;for(let i=0;i<count;i++){let diff=tape?tape[i]:Math.sin(i*2.7+1)*15+Math.cos(i*.8)*8+(i>18?-7:4);values.push({a:v,b:v+diff});v+=diff;}let all=values.flatMap(x=>[x.a,x.b]),min=Math.min(...all)-10,max=Math.max(...all)+15,y=v=>200-(v-min)/(max-min)*165;let pts=values.map((x,i)=>`${i*18+16},${y(x.b)}`).join(' ');return `<svg class="candles" preserveAspectRatio="none" viewBox="0 0 ${count*18+32} 230" role="img" aria-label="游戏内虚构市场走势，不代表真实行情"><defs><linearGradient id="fade" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#d8f36a" stop-opacity=".12"/><stop offset="100%" stop-color="#d8f36a" stop-opacity="0"/></linearGradient></defs>${[35,80,125,170,215].map(y=>`<line x1="0" x2="${count*18+32}" y1="${y}" y2="${y}" stroke="#293126" stroke-dasharray="3 5"/>`).join('')}<polyline points="${pts}" fill="none" stroke="#b5c57d" opacity=".5" stroke-width="1.3"/>${values.map((x,i)=>{let color=x.b>x.a?'#fa736a':'#58cda3';return `<line x1="${i*18+16}" x2="${i*18+16}" y1="${y(Math.max(x.a,x.b))-7}" y2="${y(Math.min(x.a,x.b))+7}" stroke="${color}"/><rect x="${i*18+11}" y="${y(Math.max(x.a,x.b))}" width="10" height="${Math.max(2,Math.abs(y(x.a)-y(x.b)))}" fill="${color}"/>`;}).join('')}</svg>`;}
function home(){return `${header()}<main class="welcome"><div class="home-layout"><section><div class="eyebrow">A-SHARE CARD ROGUELIKE</div><h1>再赚一天，<br><em>我就走。</em></h1><p>看懂行情，打出策略。<br>在牛熊之间，守住你的本金和理智。</p><div class="home-actions"><button class="primary" data-ui="${saved&&saved.screen!=='result'?'resume':'start'}">${saved&&saved.screen!=='result'?(saved.version===1?'继续旧版牌局':'继续交易'):'开始交易'} <span>↗</span></button>${saved&&saved.screen!=='result'?`<button data-ui="new">${saved.version===1?'体验新版开局':'重新开局'}</button>`:''}</div><div class="welcome-foot">¥100,000 初始本金 <span>·</span> 5–10 分钟 <span>·</span> 无需注册</div></section><section class="home-terminal"><div class="terminal-head"><span>散户情绪指数</span><span class="pill">虚构行情</span></div><div class="big-index">3,000<span>.00</span></div><div class="up index-gain">+99.99 <span>+3.45%</span><small>今天，又相信了。</small></div>${candles(true)}<div class="quote"><span>股吧热议</span>“牛市来了！这次不一样！”<b>↗</b></div><div class="terminal-bottom">从两张牌开始 <span>边玩边学</span><b>无需先读规则</b></div></section></div><div class="market-line"><span>你的下一笔交易，会改变故事。</span><span>最高资产 <strong>${money(stats.best)}</strong></span><span>穿越牛熊 <b>${stats.wins}</b> 次</span></div><footer>纯属虚构的策略游戏 · 不含真实股票与实时行情 · 不构成投资建议 · ${STATIC_PAGES?'此静态版不上传使用统计；留言请前往原站':'匿名使用统计可在设置中关闭'} ${!storageOK?'<span class="down">浏览器存储不可用，进度仅在本次页面有效</span>':''}</footer></main>`;}
function account(){const f=features(run),live=run.screen==='battle',holding=units(run)*price(run),total=live?equity(run):run.hp,cash=run.book?run.book.cash+(live?0:run.hp-run.book.equity):run.hp,ratio=total>0?holding/total*100:0;return `<section class="account portfolio ${live?'live-portfolio':''}"><div class="net"><span class="label">${live?'实时资产':'总资产'}</span><strong>${money(total)}</strong></div><button class="portfolio-position" data-ui="position" aria-label="仓位 ${ratio.toFixed(1)}%，查看持仓"><span class="label">仓位 <b>${ratio.toFixed(1)}%</b></span><span class="position-track"><i style="width:${Math.min(100,Math.max(0,ratio))}%"></i></span><small>${money(holding)}</small></button><div class="portfolio-cash"><span class="label">${cash<0?'融资':'现金'}</span><strong>${money(Math.abs(cash))}</strong></div>${f.full?`<div class="fund"><span class="label">经费</span><strong>${run.coins}</strong><button class="text-btn" data-ui="deck">卡组 ${run.deck.length}</button></div>`:''}</section>`;}

function positionSummary(){return `<div class="t1-summary"><span>持仓市值 <b>${money(units(run)*price(run))}</b></span><span>可卖旧仓 <b>${(oldUnits(run)*1000).toFixed(2)} 份</b></span><span>今日买入 <b>${((units(run)-oldUnits(run))*1000).toFixed(2)} 份</b></span><small>T+1：新买份额次日可卖；投入比例以当日开盘资产为基准。</small></div>`;}
function livePanel(){const c=run.combat,l=c.live,f=features(run),pnl=estimatedPnl(run);return `<div class="live-top"><span>今日行情 <b>${TIMES[l.step]}</b></span>${f.emotion?`<span class="mood-pill">${MOODS[l.mood]}</span>`:''}</div><div class="live-numbers"><div><strong>¥${l.price.toFixed(2)}</strong><span class="${l.value<0?'down':'up'}">${l.value>=0?'+':''}${l.value.toFixed(2)}%</span></div><div><small>今日浮盈亏</small><b class="${pnl<0?'down':'up'}">${c.hidePnl?'—':(pnl>=0?'+':'−')+money(Math.abs(pnl))}</b></div></div>${chartMarkup(run)}`;}

function tradeList(){const trades=run.combat?.trades||[];return trades.length?`<div class="trade-tape">${trades.map(t=>`<div><span>${t.time} ${esc(t.label)} · ${t.side}</span><span>${(t.units*1000).toFixed(2)} 份 × ¥${t.price.toFixed(2)} = ${money(t.amount)}</span></div>`).join('')}</div>`:'<p class="muted">暂无成交</p>';}

function nextTime(){return TIMES[slots(run).find(k=>k>run.combat.live.step)??5];}
function currentRules(){const id=run.combat.market;return ({training:'每两次收盘解锁更多时段和卡牌。',range:'今日第 2 次起调整仓位，每次支付 ¥100 交易费。',earnings:'本段行情的股息增加 30%，买卖仍按实际价格成交。',liquidity:'本段行情每次买卖支付成交额 0.2% 的流动性交易费。',rumor:'第 1 日判断消息，第 3 日揭晓，奖励或成本 ¥1,000。',boss:'最终考验：参与交易并撑过全部六个交易日。'})[id]||'未来涨跌未知。选择成交时机，参与交易并守住本金。';}
function battle(){const f=features(run),c=run.combat,m=marketFor(run),closed=c.live.step===5;return `<main class="learning-content live-battle phase-${f.level}"><div class="battle-heading"><h1>第 ${c.turn} 日 <small>/ ${m.days}</small></h1><div>${f.full?'<button class="text-btn" data-ui="market-info">行情规则</button>':''}<button class="text-btn" data-ui="log">记录</button></div></div><section class="learning-market live-market" data-live-panel>${livePanel()}</section>${effectsPanel()}<section class="learning-hand"><div class="learning-hand-head"><h2>手牌 <small>${c.hand.length}</small></h2><div class="pile-buttons">${f.level>=2?`<button class="text-btn" data-ui="draw">抽牌 ${c.draw.length}</button><button class="text-btn" data-ui="discard">弃牌 ${c.discard.length}</button>${c.exhaust?.length?`<button class="text-btn" data-ui="exhaust">消耗 ${c.exhaust.length}</button>`:''}`:''}</div></div><div class="learning-cards">${c.hand.map((card,i)=>cardHTML(card,i)).join('')||'<p class="empty-hand">手牌已用完</p>'}</div><div class="learning-close">${c.block?`<button class="text-btn hedge-balance" data-ui="position">对冲 ${money(c.block)}</button>`:'<span></span>'}<button class="primary" data-action="${closed?'end':'advance'}">${closed?'收盘结算':nextTime()+' 继续'}</button></div></section>${f.full?`<div class="live-extras"><button data-action="tool" ${run.toolUsed||closed?'disabled':''}>${run.toolUsed?'对冲已用':'应急对冲 · ¥500'}</button><button data-ui="habits" class="text-btn">投资习惯 ${run.relics.length}</button><button data-ui="abandon" class="text-btn">离场</button>${c.market==='rumor'&&c.turn===1&&c.rumorBet===null?'<button data-action="bet" data-value="true">相信小作文</button><button data-action="bet" data-value="false">不相信</button>':''}</div>`:''}</main>`;}

function buildView(){return `<main class="content build-page"><h1>选择你的打法</h1><p>三张核心牌加入卡组。</p><div class="build-options">${BUILDS.map(b=>`<button class="build-option" data-action="build" data-id="${b.id}"><h2>${b.name}</h2><p>${b.text}</p><div>${(run?.version===4?(b.expandedCards||b.cards):b.cards).map(id=>`<small>${CARD[id].name}</small>`).join('')}</div></button>`).join('')}</div></main>`;}

function topSection(k,title,desc){return `<div class="section-title"><div><span class="eyebrow">${k}</span><h1>${title}</h1><p>${desc}</p></div><div class="chapter">第 <b>${String(run.layer+1).padStart(2,'0')}</b> / ${String(run.map.length).padStart(2,'0')} 站</div></div>`;}
function mapView(){return `<main class="content map-content">${topSection('THE MARKET CYCLE','选一条路，走进市场。','')}<div class="map-layout"><section class="route-map" aria-label="行情路线图">${run.map.map((row,i)=>`<div class="map-row ${i===run.layer?'current':''} ${i<run.layer?'past':''}"><span class="row-no">${String(i+1).padStart(2,'0')}</span><div class="map-nodes">${row.map(n=>`<button class="map-node ${run.path.includes(n.id)?'visited':''} ${n.type==='boss'?'boss-node':''}" data-action="enter" data-id="${n.id}" ${i!==run.layer?'disabled':''}><span class="node-symbol">${run.path.includes(n.id)?'✓':NODE_ICONS[n.type]}</span><span><small>${NODE_LABELS[n.type]}</small><b>${n.type==='market'||n.type==='elite'||n.type==='boss'?'未来走势未知':n.type==='event'?'未知的小道消息':n.type==='rest'?'休息 / 升级':'补强你的策略'}</b></span>${i===run.layer?'<span class="node-arrow">↗</span>':''}</button>`).join('')}</div>${i===run.layer?'<span class="here">你在这里</span>':''}</div>`).join('')}</section><aside class="map-aside"><div class="panel habit-panel"><h3>你的投资习惯 <small>${run.relics.length} 件</small></h3>${relicList()}</div><button class="text-btn muted" data-ui="abandon">结束本轮投资生涯 ↗</button></aside></div></main>`;}
function relicList(){return run.relics.map(id=>`<button class="habit" data-ui="relic" data-id="${id}"><i>${RELIC[id].icon}</i><span>${RELIC[id].name}<small>${RELIC[id].text}</small></span></button>`).join('');}
function cardHTML(card,index,mode='play'){const d=CARD[card.id],meta=design(card.id),text=mode==='play'&&['probe','add','reduce','watch'].includes(d.id)?({probe:`投入 ${card.up?'13.5':'10'}% 买入。下一张买入牌投入 +${card.up?'50':'30'}%。`,add:`投入 ${card.up?'27':'20'}% 买入。`,reduce:`卖出 ${card.up?'27':'20'}% 旧仓。`,watch:`抽 ${card.up?'3':'2'} 张牌。`})[d.id]:cardText(run,d,card),reason=mode==='play'?tradingRestriction(run,card):'',disabled=!!reason,combo=mode==='play'&&!disabled?comboFor(run,d.id):null,conflict=reason.includes('T+1')?'T+1':reason.includes('旧仓')?'无可卖旧仓':reason.includes('锁仓')?'锁仓中':reason.includes('现金')?'现金不足':reason.includes('需要未用对冲')?'需要对冲':'';const attrs=mode==='play'?`data-action="play" data-index="${index}" data-uid="${card.uid}" data-card="${d.id}"`:mode==='reward'?`data-action="reward" data-id="${d.id}"`:mode==='upgrade'?`data-ui="upgrade-preview" data-uid="${card.uid}"`:mode==='remove'?`data-action="remove" data-uid="${card.uid}" data-card="${d.id}"`:'';const tag=mode==='view'||mode==='compare'?'article':'button',foot=mode==='reward'?'收入卡组':mode==='upgrade'?'对比强化效果':mode==='remove'?'移除 · 30 经费':mode==='play'?(disabled?'':'打出'):'策略档案';
 const body=`<${tag} class="strategy-card category-${meta.key} rarity-${meta.rarity} ${card.up?'upgraded':''}" style="--card-accent:${meta.color}" ${attrs} ${disabled?`disabled title="${esc(reason)}"`:''} ${tag==='button'?`aria-label="${d.name}${card.up?'强化版':''}，${meta.category}，${meta.label}，${text}"`:''}><div class="card-top"><span class="card-kind">${meta.icon} ${meta.category}</span><span class="rarity-badge">${meta.mark} ${meta.label}</span></div><div class="card-art"><span>${meta.icon}</span><small>${meta.archetype}</small>${card.up?'<b class="upgrade-seal">强化 +</b>':''}</div><div class="card-copy"><h3>${d.name}${card.up?'<sup>+</sup>':''}</h3><p>${esc(text)}</p>${conflict?`<small class="card-conflict">${conflict}</small>`:''}${combo?`<span class="combo-badge">${combo.label}</span>`:''}</div><div class="card-tags">${meta.exhaust?'<span title="打出后本场不再抽到，下个行情节点恢复">消耗</span>':''}</div><div class="card-footer">${foot}${mode==='play'?`<small>${index+1}</small>`:''}</div></${tag}>`;
 return mode==='compare'?body:`<div class="card-slot">${body}<button class="card-detail-link" data-ui="card-detail" data-id="${d.id}" ${card.uid?`data-uid="${card.uid}"`:''} data-up="${!!card.up}">详情</button></div>`;}
function effectsPanel(){const c=run.combat,active=c.effects||[];if(!active.length&&!c.dividendRate&&!c.retained&&!(c.yieldBoost>1))return '';return `<section class="effects-panel" aria-label="持续策略"><div class="effect-chips">${c.dividendRate?`<button class="effect-chip category-yield" data-ui="position"><b>股息 ${(c.dividendRate*100).toFixed(2)}%</b></button>`:''}${active.map(e=>`<button class="effect-chip category-${design(e.id).key}" data-ui="card-detail" data-id="${e.id}" style="--card-accent:${design(e.id).color}" title="${effectSummary(e)}"><b>${CARD[e.id].name}</b>${e.remaining!==null?`<small>${e.remaining} 次</small>`:''}</button>`).join('')}${c.retained?'<span class="effect-chip">留牌</span>':''}${c.yieldBoost>1?`<span class="effect-chip category-yield">股息 ×${c.yieldBoost}</span>`:''}</div></section>`;}

function categoryLegend(){return `<div class="category-legend" aria-label="卡牌类型颜色说明">${Object.entries(CATEGORIES).filter(([k])=>features(run).full||run.deck.some(c=>design(c.id).category===k)).map(([k,v])=>`<span style="--card-accent:${v.color}">${v.icon} ${k}</span>`).join('')}<button class="text-btn" data-ui="keywords">类型与关键词</button></div>`;}

function reward(){return `<main class="content centered">${topSection('CYCLE COMPLETED','你还在牌桌上。',`获得 ${run.node.type==='elite'?45:25} 研究经费。选择一张策略牌，或者保持克制。`)}${run.reward.relic?`<div class="relic-reward">获得投资习惯：<b>${RELIC[run.reward.relic].name}</b><span>${RELIC[run.reward.relic].text}</span></div>`:''}<div class="reward-cards">${run.reward.cards.map(id=>cardHTML({id},0,'reward')).join('')}</div><button data-action="reward">跳过奖励，继续前进 →</button></main>`;}
function eventView(){let e=EVENTS[run.node.event];return `<main class="content event-page">${topSection('BREAKING RUMOR','消息来了。','消息是免费的，代价是后来的。')}<section class="event-paper"><div class="paper-masthead">韭菜晚报 <span>消息未经核实 / 第 ${run.layer+1} 期</span></div><span class="event-number">?</span><h2>${e.name}</h2><blockquote>${e.quote}</blockquote><div class="event-choices">${e.choices.map(([name,desc],i)=>`<button data-action="event" data-index="${i}"><span>${name}<small>${desc}</small></span><b>↗</b></button>`).join('')}</div></section></main>`;}
function shop(){return `<main class="content">${topSection('BROKERAGE STORE','券商只赚手续费。','而你，可以在这里买到一点胜算。每种商品限购一次。')}<div class="shop-grid">${run.shop.cards.map(id=>`<div class="shop-item">${cardHTML({id},0,'view')}<button data-action="buy" data-id="${id}" data-kind="card" ${run.coins<cardPrice(id)||run.shop.bought.includes('c:'+id)?'disabled':''}>${run.shop.bought.includes('c:'+id)?'已收入卡组':'购买 · '+cardPrice(id)+' 经费'}</button></div>`).join('')}</div><div class="shop-extras">${run.shop.relic?`<div class="panel"><span class="eyebrow">投资习惯</span><h3>${RELIC[run.shop.relic].name}</h3><p>${RELIC[run.shop.relic].text}</p><button data-action="buy" data-kind="relic" data-id="${run.shop.relic}" ${run.coins<65||run.shop.bought.includes('r:'+run.shop.relic)?'disabled':''}>${run.shop.bought.includes('r:'+run.shop.relic)?'已购买':'购买 · 65 经费'}</button></div>`:''}<div class="panel"><span class="eyebrow">账户整理</span><h3>忘掉一种策略</h3><p>永久移除一张卡，每家商店限一次。卡组至少保留 5 张。</p><button data-ui="remove" ${run.coins<30||run.shop.removed||run.deck.length<=5?'disabled':''}>${run.shop.removed?'本店已整理':'选择删牌 · 30 经费'}</button></div></div><button class="primary" data-action="leave">离开商店 →</button></main>`;}
function rest(){return `<main class="content centered">${topSection('AFTER-HOURS REVIEW','收盘后，想清楚。','你可以修复账户，也可以修正策略。二选一。')}<div class="rest-options"><button class="rest-option" data-action="rest"><span>◷</span><small>TAKE A BREAK</small><h2>泡杯茶，离开屏幕</h2><p>恢复 ¥24,000<br>贪婪降低 2</p><b>好好休息 ↗</b></button><button class="rest-option" data-ui="upgrade"><span>↗</span><small>REFINE YOUR STRATEGY</small><h2>复盘，不是后悔</h2><p>升级一张策略牌<br>增加数值、触发次数或策略能力<br>先预览，再确认</p><b>选择升级 ↗</b></button></div><button class="text-btn" data-action="leave">什么也不做，继续前进 →</button></main>`;}
function careerChart(){let a=run.history,min=Math.min(...a,run.hp),max=Math.max(...a),range=max-min||1;let pts=a.map((v,i)=>`${20+i/(Math.max(1,a.length-1))*700},${160-(v-min)/range*130}`).join(' ');return `<svg viewBox="0 0 740 190" role="img" aria-label="本轮资产走势，最高 ${money(run.peak)}，最终 ${money(run.hp)}"><line x1="20" x2="720" y1="160" y2="160" stroke="#394131"/><polyline points="${pts}" fill="none" stroke="${run.won?'#d8f36a':'#58cda3'}" stroke-width="3"/><text x="20" y="184" fill="#98a191" font-size="12">开盘</text><text x="680" y="184" fill="#98a191" font-size="12">收盘</text></svg>`;}
function result(){let favorite=Object.entries(run.used).sort((a,b)=>b[1]-a[1])[0];return `<main class="content result-page"><span class="eyebrow">YOUR TRADING CAREER</span><h1>${run.won?'活着穿越牛熊。':'你曾经赚到过。'}</h1><p class="result-sub">本轮投资生涯 · ${run.won?'成功通关':'本轮结束'}</p><div class="result-total"><span>最终资产</span><strong class="${run.hp>=100?'up':'down'}">${money(run.hp)}</strong><small>${run.cause}</small></div><div class="result-chart">${careerChart()}</div><div class="result-stats"><div><span>初始资产</span><b>¥100,000</b></div><div><span>最高资产</span><b>${money(run.peak)}</b></div><div><span>最大盈利</span><b class="up">+${(run.peak-100).toFixed(1)}%</b></div><div><span>最大回撤</span><b class="down">−${(run.maxDrawdown*100).toFixed(1)}%</b></div><div><span>最常使用</span><b>${favorite?CARD[favorite[0]].name:'观望市场'}</b></div><div><span>存活交易日</span><b>${run.rounds} 日</b></div></div><blockquote>“${run.won?'赚得多是运气，走得掉是本事。':['如果那时候卖了就好了。','回本只差一点点。','下次一定。'][run.rounds%3]}”</blockquote><button class="primary" data-ui="start">再来一轮 ↗</button><button class="text-btn" data-ui="home">回到首页</button></main>`;}
function render(){motion.configure(prefs.motion,prefs.motionMode==='full');audio.configure(prefs,!!run&&run.screen!=='result');document.documentElement.classList.toggle('no-motion',!prefs.motion);document.documentElement.classList.toggle('force-motion',prefs.motionMode==='full');root.innerHTML=run?header()+account()+({map:mapView,battle,reward,event:eventView,shop,rest,result,build:buildView}[run.screen])():home();telemetry.view({screen:run?.screen||'home',run:run?.runId||'',stage:run?stage(run):0,day:run?run.rounds+1:0});if(!storageOK)notify('浏览器存储不可用，请勿关闭页面。');}
function openModal(type,id){if(run&&!features(run).full&&!['settings','help','position','market-info','feedback','log','draw','discard','exhaust','card-detail','keywords','new','abandon'].includes(type)){notify('完成开盘练习后开放。');return;}modal={type,id};let title='',body='';if(type==='position'){const c=run.combat;title='持仓';body=`${positionSummary()}${c?.block?`<p>可用对冲 ${money(c.block)}</p>`:''}${c?.dividendRate?`<p>基础股息率 ${(c.dividendRate*100).toFixed(3)}%</p>`:''}<p class="muted">仓位 = 持仓市值 ÷ 实时资产。盘中资产随价格变化；股息、利息及对冲在收盘入账。</p>${c?tradeList():''}<button class="text-btn" data-ui="help">交易规则</button>`;}else if(type==='market-info'){title='行情规则';body=`<p>${currentRules()}</p>`;}else if(type==='help'){title='先看懂成交，再看懂盈亏';body=`<div class="help-grid"><section><b>时间由你推进</b><p>初期 09:30、13:00 各一次出牌机会；随后开放 10:30、14:00。每时段只能出一张，跳过不会积攒。按按钮才变化，阅读、切换页面都不会偷偷走时。</p></section><section><b>买入不赠送收益</b><p>开盘资产 ¥100,000，投入 20% 就是拿 ¥20,000 买入。在 ¥100 买到 200 份，¥102 收盘赚 ¥400；¥98 收盘亏 ¥400。买入资金只是从现金转为持仓。</p></section><section><b>成交价决定损益</b><p>盘中记录买卖份数与实际成交价。卖出旧仓的部分按卖出价计算，未卖部分按收盘价计算。跨日持仓以昨收作为本日计价基准，避免重复计算昨日收益。</p></section><section><b>T+1 与资金</b><p>今天新买的份额明天才能卖。卖出旧仓后资金可继续买入；普通买入不超过现金，融资牌可借钱但需要支付利息。</p></section><section><b>连招放大投入</b><p>小仓试探后，本日下一张买入牌投入金额增加 30%。加仓由开盘资产 20% 变为 26%，后续盈亏一起放大；不改变成交价格，也没有固定 ¥6,000 奖励。</p></section><section><b>收盘统一对账</b><p>盘中显示浮动估值，上次结算资产不变。收盘按价差计算本日盈亏，再加股息、扣融资或对冲成本。对冲只覆盖当日净交易亏损；股息是按持仓市值计算的游戏机制。</p></section></div>`;}

else if(type==='keywords'){title='看懂牌面';body=`<div class="keyword-list">${Object.entries(CATEGORIES).map(([k,v])=>`<p><b style="color:${v.color}">${v.icon} ${k}</b> ${v.hint}</p>`).join('')}<hr><p><b>基础 / 普通 / 罕见 / 稀有</b> 表示获得概率与商店价格，不保证稀有牌适合当前构筑。精英奖励至少有一张稀有牌。</p><p><b>消耗</b> 打出后本场不再抽到，下个行情节点恢复，卡组不会永久失去这张牌。</p><p><b>本场持续</b> 当前行情节点的多日效果，离开节点失效。倒数按指定的开盘或收盘次数计算。</p><p><b>保留</b> 剩余手牌留到次日，再照常抽牌；手牌最多 10 张。</p><p><b>强化 +</b> 每张牌可强化一次。复盘室先选择卡牌查看前后差异，再确认强化。</p><p><b>股息再投</b> 只把收到的股息转换成持仓，收益不会被记两遍。多个再投效果合计最多 100%；新仓遵守 T+1。</p></div>`;}
else if(type==='card-detail'||type==='upgrade-preview'){const card=type==='upgrade-preview'?run.deck.find(c=>c.uid===Number(id)):id?.uid?(run?.deck.find(c=>c.uid===id.uid)||{id:id.id,up:id.up}):{id:typeof id==='string'?id:id.id,up:!!id?.up};if(!card||!CARD[card.id])return;const d=CARD[card.id],meta=design(card.id),upgrade=canUpgrade(card.id)&&!card.up;title=type==='upgrade-preview'?'确认强化 · '+d.name:d.name+' · '+meta.category;body=`<p class="muted">${meta.mark} ${meta.label} · ${meta.archetype} · ${meta.hint}</p><div class="upgrade-comparison"><section><h3>${card.up?'当前强化版':'当前牌效'}</h3>${cardHTML(card,0,'compare')}</section>${upgrade?`<section><h3>强化后</h3>${cardHTML({...card,up:true},0,'compare')}</section>`:''}</div><p class="muted">${meta.exhaust?'消耗：打出后进入消耗区，本场不会再抽到。':''} 买卖比例以当日开盘资产为基准；卖出只处理旧仓。每张牌占一个交易时段，自动触发不占时段。手牌上限 10 张。</p>${type==='upgrade-preview'&&upgrade?`<button class="primary" data-action="upgrade" data-uid="${card.uid}">确认强化 ${d.name}+</button>`:''}`;}
else if(type==='settings'){title='交易偏好';body=`<div class="setting"><span>牌桌音效<small>现成翻牌与筹码录音；结算时变速、变调</small></span><button data-ui="sound" role="switch" aria-checked="${prefs.sound}">${prefs.sound?'已开启':'已关闭'}</button></div><label class="volume-control">音效音量 <output>${Math.round(prefs.soundVolume*100)}%</output><input aria-label="音效音量" data-volume="soundVolume" type="range" min="0" max="100" value="${Math.round(prefs.soundVolume*100)}"></label><p class="muted">背景音乐已停用，仅保留操作音效。</p><label class="motion-mode">动画强度<select data-motion-mode aria-label="动画强度"><option value="auto" ${!prefs.motionMode||prefs.motionMode==='auto'?'selected':''}>跟随系统</option><option value="full" ${prefs.motionMode==='full'?'selected':''}>完整动画</option><option value="reduced" ${prefs.motionMode==='reduced'?'selected':''}>减少动态</option></select></label><p class="muted">${matchMedia('(prefers-reduced-motion: reduce)').matches?'系统当前开启了减少动态效果。选择完整动画可在本游戏中启用飞牌和震动。':'结算流水始终显示；减少动态时关闭飞牌与震动。'}</p>${STATIC_PAGES?'<p class="muted">此静态版不上传使用统计。留言会在新标签页打开原 A 股站点，当前进度仍保留在这里。</p>':`<div class="setting"><span>匿名使用统计<small>记录访问、卡牌和操作时长；不记录姓名、键盘输入、IP 或完整浏览记录。</small></span><button data-ui="analytics" role="switch" aria-checked="${prefs.analytics}">${prefs.analytics?'已开启':'已关闭'}</button></div>`}<details class="audio-credits"><summary>音效来源 / 免费授权</summary><p><a href="https://kenney.nl/assets/casino-audio" target="_blank" rel="noopener">Casino Audio · Kenney</a>，CC0。转码为 MP3，并在播放时变速变调。<a href="./assets/audio/CREDITS.txt" target="_blank">完整署名</a></p></details>`;}
else if(type==='feedback'){title='给这位散户留句话';body=`<form id="feedback-form"><label>这次体验<select name="rating"><option value="5">5 · 很有意思</option><option value="4">4 · 还不错</option><option value="3" selected>3 · 还有改进空间</option><option value="2">2 · 没太玩明白</option><option value="1">1 · 遇到了问题</option></select></label><label>留言<textarea name="message" required minlength="2" maxlength="1500" rows="5" placeholder="哪张牌看不懂？哪个操作别扭？也可以说说你想玩的连招。"></textarea></label><input name="website" class="honeypot" tabindex="-1" autocomplete="off" aria-hidden="true"><p class="muted">留言仅开发者可见，无需留下个人信息。失败时保留内容，可重新发送。</p><p class="feedback-status" role="status"></p><button class="primary" type="submit">发送留言</button></form>`;}
else if(type==='codex'){title=`策略档案 / ${CARDS.length} 张卡牌`;body=`<div class="codex-summary">已收集 ${stats.unlocked.length} / ${CARDS.length}</div><div class="codex-tabs">${['全部',...Object.keys(CATEGORIES),'普通','罕见','稀有','强化','组合','习惯'].map(t=>`<button data-ui="filter" data-id="${t}" class="${(id||'全部')===t?'selected':''}">${t}</button>`).join('')}</div>${id==='组合'?`<div class="combo-catalog">${COMBOS.map(c=>`<section><h3>${c.name}</h3><p>${c.text}</p><div>${c.ids.map(id=>`<button data-ui="card-detail" data-id="${id}">${CARD[id].name}</button>`).join('')}</div></section>`).join('')}</div>`:id==='习惯'?`<div class="relic-catalog">${RELICS.map(r=>`<div class="panel"><h3>${r.icon} · ${r.name}</h3><p>${r.text}</p></div>`).join('')}</div>`:`<div class="card-grid">${CARDS.filter(c=>!id||id==='全部'||design(c.id).category===id||design(c.id).label===id||(id==='强化'&&canUpgrade(c.id))).map(c=>cardHTML({...c,up:id==='强化'},0,'view')).join('')}</div>`}`;}
else if(['deck','draw','discard','exhaust','upgrade','remove'].includes(type)){title={deck:'你的完整卡组',draw:'抽牌堆 · 不显示抽取顺序',discard:'弃牌堆',exhaust:'消耗区 · 本场不再抽到',upgrade:'选择一张策略升级',remove:'选择一张策略移除'}[type];let list=type==='draw'?[...run.combat.draw].sort((a,b)=>a.id.localeCompare(b.id)):type==='discard'?run.combat.discard:type==='exhaust'?(run.combat.exhaust||[]):run.deck;list=list.filter(c=>type==='upgrade'?!c.up&&canUpgrade(c.id):type==='remove'?!(run.relics.includes('old')&&STARTER.includes(c.id)):true);body=`${type==='upgrade'?'<p class="muted">每张牌有独立的强化效果：可能增加投入、股息、抽牌或持续次数。选择后先对比，再确认；每张牌只能强化一次。</p>':''}<div class="card-grid">${list.map((c,i)=>cardHTML(c,i,['upgrade','remove'].includes(type)?type:'view')).join('')||'<p>这里暂时没有卡牌。</p>'}</div>`;}
else if(type==='habits'){title='投资习惯';body=`<div class="habit-panel">${relicList()}</div>`;}
else if(type==='relic'){title=RELIC[id].name;body=`<p>${RELIC[id].text}</p>`;}
else if(type==='log'){title='交易记录';body=`${run.combat?tradeList():''}<ol class="log-list">${run.log.map(t=>`<li>${esc(t)}</li>`).join('')}</ol>`;}
else if(type==='abandon'||type==='new'){title=type==='new'?'重新开始一轮？':'现在离场？';body=`<p>${type==='new'?'当前牌局会被新一轮覆盖。历史最高资产和通关记录会保留。':'本轮生涯将立即结算，之后可以重新开局。'}</p><button class="primary" data-ui="${type==='new'?'confirm-new':'confirm-abandon'}">${type==='new'?'确认重新开局':'确认离场'}</button>`;}
$('#modal')?.remove();let d=document.createElement('dialog');d.id='modal';d.innerHTML=`<div class="modal-head"><h2 id="modal-title">${title}</h2><button data-ui="close" aria-label="关闭弹窗">×</button></div><div class="modal-body">${body}</div>`;d.setAttribute('aria-labelledby','modal-title');document.body.append(d);d.addEventListener('click',e=>{if(e.target===d)closeModal();});d.addEventListener('cancel',()=>modal=null);d.showModal();}
function closeModal(){modal=null;$('#modal')?.close();$('#modal')?.remove();}
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b||b.disabled)return;audio.unlock();if(b.dataset.action){let a={type:b.dataset.action};if(b.dataset.id)a.id=b.dataset.id;if(b.dataset.index!==undefined)a.index=Number(b.dataset.index);if(b.dataset.uid)a.uid=Number(b.dataset.uid);if(b.dataset.kind)a.kind=b.dataset.kind;if(b.dataset.value!==undefined)a.value=b.dataset.value==='true';closeModal();dispatch(a);return;}let ui=b.dataset.ui;if(!ui)return;telemetry.emit('ui_click',ui);if(!['sound','music','mute'].includes(ui))sound('click');switch(ui){case'card-detail':openModal('card-detail',{id:b.dataset.id,uid:b.dataset.uid?Number(b.dataset.uid):null,up:b.dataset.up==='true'});break;case'upgrade-preview':openModal('upgrade-preview',Number(b.dataset.uid));break;case'analytics':if(STATIC_PAGES)break;prefs.analytics=!prefs.analytics;telemetry.setEnabled(prefs.analytics);persist();openModal('settings');break;case'start':case'confirm-new':closeModal();start();break;case'resume':run=saved;render();motion.enter();sound('draw');if(run.combat?.triggers?.length){audio.effect('power',{rate:1.15,level:.5});motion.animate($('.effects-panel'),[{filter:'brightness(1.6)'},{filter:'brightness(1)'}],{duration:800});}break;case'home':motion.clear();run=null;render();break;case'close':closeModal();break;case'confirm-abandon':closeModal();dispatch({type:'abandon'});break;case'mute':{const on=!prefs.sound;prefs.sound=on;persist();render();if(on)sound('click');break;}case'sound':prefs[ui]=!prefs[ui];persist();render();if(ui==='sound')sound('click');openModal('settings');break;case'motion':prefs.motion=!prefs.motion;persist();render();openModal('settings');break;case'filter':openModal('codex',b.dataset.id);break;default:openModal(ui,b.dataset.id);}});
document.addEventListener('input',e=>{const key=e.target.dataset.volume;if(!['soundVolume','musicVolume'].includes(key))return;prefs[key]=Number(e.target.value)/100;e.target.parentElement.querySelector('output').textContent=e.target.value+'%';audio.configure(prefs);persist();});
document.addEventListener('keydown',e=>{audio.unlock();if(modal||run?.screen!=='battle'||e.repeat||e.ctrlKey||e.metaKey||e.altKey||e.target.matches('input,select,textarea'))return;if(/^[1-9]$/.test(e.key)){e.preventDefault();dispatch({type:'play',index:Number(e.key)-1},'keyboard');}if(e.code==='Space'&&!e.target.closest('button,a,summary')){e.preventDefault();dispatch({type:run.combat.live.step===5?'end':'advance'},'keyboard');}});
const ctx=document.modelContext;if(ctx?.registerTool){const lifecycle=new AbortController();const register=t=>{try{Promise.resolve(ctx.registerTool(t,{signal:lifecycle.signal})).catch(()=>{});}catch{}};register({name:'read_trading_state',description:'读取当前韭菜尖塔牌局和已经发生的盘中行情，不提供未来走势。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({screen:settling?'settlement':run?.screen||'home',assets:run?.hp?run.hp*1000:0,position:run&&features(run).position?run.position:undefined,greed:run&&features(run).greed?run.greed:undefined,stage:run?stage(run):0,intent:run?.combat?intent(run):null,hand:run?.combat?.hand.map(c=>({name:CARD[c.id].name,cost:cardCost(run,c)}))||[]})});register({name:'play_strategy_card',description:'打出当前手牌中指定位置的一张策略牌，占用当前交易时段并按当前点位成交，收盘核算损益。index 从 0 开始。',inputSchema:{type:'object',properties:{index:{type:'integer',minimum:0,maximum:9}},required:['index'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{if(!Number.isInteger(input?.index)||run?.screen!=='battle'||!run.combat.hand[input.index])throw Error('无效的手牌位置');if(gate.busy||settling||advancing)throw Error('出牌反馈中，请稍后再出牌');act(run,{type:'play',index:input.index});if(!dispatch({type:'play',index:input.index},'webmcp'))throw Error('出牌未完成');return {assets:run.hp*1000,energy:run.combat.energy};}});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
document.addEventListener('change',e=>{if(e.target.matches('[data-motion-mode]')){prefs.motionMode=e.target.value;prefs.motion=e.target.value!=='reduced';persist();motion.configure(prefs.motion,prefs.motionMode==='full');document.documentElement.classList.toggle('force-motion',prefs.motionMode==='full');document.documentElement.classList.toggle('no-motion',!prefs.motion);}});
document.addEventListener('pointerdown',e=>{const b=e.target.closest('[data-action]');if(b?.disabled){const target=b.dataset.action==='play'?'card:'+b.dataset.card:b.dataset.action;telemetry.action('action_attempt',target,{input:'pointer',exposure:`${run?.runId}-${(run?.rounds||0)+1}-${b.dataset.uid}`});telemetry.action('action_rejected',target,{reason:b.querySelector('.card-conflict')?.textContent||'尚未收盘',input:'pointer'});}});
let hovering=null;document.addEventListener('pointerover',e=>{const c=e.target.closest('[data-action="play"]');if(!c||hovering?.el===c)return;telemetry.clock();hovering={el:c,id:c.dataset.card,time:telemetry.pageTime};});document.addEventListener('pointerout',e=>{if(hovering&&!hovering.el.contains(e.relatedTarget)){telemetry.clock();telemetry.emit('card_focus','card:'+hovering.id,{activeMs:Math.round(telemetry.pageTime-hovering.time)});hovering=null;}});
document.addEventListener('submit',async e=>{if(e.target.id!=='feedback-form')return;e.preventDefault();if(STATIC_PAGES)return;const form=e.target,button=form.querySelector('button'),status=form.querySelector('.feedback-status');button.disabled=true;status.textContent='正在发送…';const fields=new FormData(form);form.dataset.messageId??=crypto.randomUUID();try{const r=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:form.dataset.messageId,session:telemetry.session,screen:run?.screen||'home',message:fields.get('message'),rating:Number(fields.get('rating')),website:fields.get('website')})});const data=await r.json();if(!r.ok)throw Error(data.error||'发送失败');status.textContent='留言已收到，谢谢。';form.querySelector('textarea').value='';delete form.dataset.messageId;}catch(e){status.textContent=e.message||'网络暂时不可用，内容已保留。';}finally{button.disabled=false;}});
render();
