import {offerCards,cardPrice,canUpgrade} from './card-design.js?v=82ac3ff11395dbeeecb02c3d06dcb66bd310dc05';
import {triggerOpening,TRADE_UPGRADABLE,initBook,startBookDay,syncBook,slots,playTrading,settleTrading} from './trading.js?v=82ac3ff11395dbeeecb02c3d06dcb66bd310dc05';
import {startManualTape,advanceTape,startTape,tickTape,publicQuote,availablePosition,tradingRestriction} from './live-market.js?v=82ac3ff11395dbeeecb02c3d06dcb66bd310dc05';
import {stage,features,marketFor,STAGES,BUILDS} from './progression.js?v=82ac3ff11395dbeeecb02c3d06dcb66bd310dc05';
import {CARD,CARDS,STARTER,RELICS,MARKETS,EVENTS} from './data.js?v=82ac3ff11395dbeeecb02c3d06dcb66bd310dc05';
export const UPGRADABLE=['probe','reduce','watch','profit','bottom','chase','empty','break','confirm','left','dip','panic','gold','bank','coal','dividend','cash','value','limit','inverse','contrary','cashout'];
export const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export const exposure=p=>p===0?0:p<=20?p/40:p<=50?.5+(p-20)/60:p<=100?1+(p-50)/100:1.5+(p-100)/100;
const greedyGain=[1,1.1,1.25,1.4,1.65,2],greedyLoss=[1,1.1,1.25,1.5,2,3];
function rand(s){s.seed=(Math.imul(1664525,s.seed)+1013904223)>>>0;return s.seed/4294967296;}
function shuffle(s,a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(rand(s)*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function log(s,t){s.log=[t,...s.log].slice(0,35);s.notice=t;}
export function createRun(seed=Date.now()){let s={version:2,seed:seed>>>0,screen:'map',hp:100,peak:100,maxDrawdown:0,position:30,greed:0,coins:50,deck:['probe','reduce','probe','reduce'].map((id,i)=>({id,uid:i+1,up:false})),uid:5,relics:[],unlockedStage:0,statuses:{},layer:0,path:[],used:{},rounds:0,history:[100],log:[],notice:'开盘了。先活下来，再谈财务自由。',lastProfit:false,lastDown:false,won:false};s.map=[['market'],['event'],['shop','rest'],['market'],['elite','market'],['rest'],['boss']].map((ts,row)=>ts.map((type,col)=>({id:`${row}-${col}`,type,market:row===0?'training':type==='market'?shuffle(s,MARKETS.filter(m=>!m.elite&&!m.boss))[0].id:type==='elite'?(rand(s)>.5?'rumor':'quant'):'boss',event:Math.floor(rand(s)*EVENTS.length)})));enter(s,s.map[0][0]);return s;}
export function createLiveRun(seed=Date.now()){return migrateRun(createRun(seed),true);}
export function migrateRun(input,fresh=false){const s=structuredClone(input);if(s.version===4)return s;s.legacyRoute=s.version===1||s.legacyRoute;s.version=4;s.runId??=String(s.seed)+'-'+Date.now();s.boughtToday=0;s.notice='手动交易已就绪：时间只在点击推进后变化。买卖按当前点位成交，收盘核算损益。';if(fresh){s.position=0;s.deck=['probe','add','probe','reduce'].map((id,i)=>({id,uid:i+1,up:false}));s.combat.hand=s.deck.slice(0,2);s.combat.draw=s.deck.slice(2);s.combat.discard=[];}initBook(s);if(s.combat){startManualTape(s);s.combat.startHp=s.hp;s.combat.debts=[];s.combat.dividendRate=0;startBookDay(s);}delete s.lastSettlement;return s;}

function ledger(s,label,amount,formula=''){if(s.version>=3&&s.combat&&amount)s.combat.dayLedger.push({label,amount:Math.round(amount*1000),formula,card:s.combat.currentCard||null});}
function has(s,id){return s.relics.includes(id);}
function record(s){s.peak=Math.max(s.peak,s.hp);s.maxDrawdown=Math.max(s.maxDrawdown,(s.peak-s.hp)/s.peak);}
function gain(s,n,fixed=false,type='',sector='综合'){if(s.screen==='result'&&!s.won)return 0;let c=s.combat;let mult=fixed?1:((s.version===3||features(s).position)?exposure(s.position):1)*greedyGain[features(s).greed?s.greed:0]*(type?(c?.boost||1):1)*(c?.faith&&(s.version!==3||type)?1.5:1)*(c?.stable>=2&&has(s,'book')?1.5:1)*(type==='反指'&&has(s,'reverse')?1.3:1)*(c?.market==='rotation'&&sector===hotSector(s)?1.5:1)*(c?.market==='earnings'&&type==='红利'?1.3:1);let v=s.version===3?Math.round(n*mult*1000)/1000:Math.round(n*mult*10)/10;s.hp+=v;if(c){c.alpha+=v;c.todayGain+=v;if(!fixed&&type&&v>0)c.boost=1;}ledger(s,c?.currentCard?CARD[c.currentCard].name:(c?.ledgerLabel||'行情收益'),v,fixed?'固定金额':`基础 ¥${Math.round(n*1000)} × 倍率 ${mult.toFixed(6).replace(/\.?0+$/,'')}（四舍五入至元）`);record(s);if(v>0)log(s,`策略入账 +¥${Math.round(v*1000).toLocaleString('zh-CN')}`);return v;}
function heal(s,v){if(s.screen==='result')return;s.hp+=v;ledger(s,'账户修复',v);record(s);log(s,`账户增加 ¥${Math.round(v*1000).toLocaleString('zh-CN')}`);}
function loss(s,n,market=false,unblockable=false){const c=s.combat;let v=n;if(market){v*=((s.version===3||features(s).position)?exposure(s.position):1)*greedyLoss[features(s).greed?s.greed:0]*(c.doubleRisk?2:1);c.doubleRisk=false;}if(has(s,'helmet')&&c&&!c.helmetUsed){v=Math.max(0,v-3);c.helmetUsed=true;}if(s.version!==3&&!unblockable&&c){const b=Math.min(c.block,v);c.block-=b;v-=b;}v=s.version===3?Math.round(v*1000)/1000:Math.round(v*10)/10;if(c?.defer&&market&&v>0){c.debts.push({due:c.turn+3,amount:v});log(s,`¥${Math.round(v*1000).toLocaleString("zh-CN")} 亏损将于第 ${c.turn+3} 日结算（离场即结清）`);return;}if(s.version===3&&market&&c){const hedge=Math.min(c.block,v);c.block-=hedge;s.hp+=hedge;ledger(s,'对冲兑现',hedge,'上限为今日市场亏损与对冲额度中的较小值');}const actual=Math.min(s.hp,v);s.hp=Math.max(0,s.hp-v);ledger(s,market?'持仓回撤':c?.currentCard?CARD[c.currentCard].name+' · 成本/损失':'其他支出',-actual);record(s);if(v)log(s,`账户亏损 −¥${Math.round(v*1000).toLocaleString('zh-CN')}`);if(s.hp<=0)finish(s,false,market?`${s.position}% 仓位 + 贪婪 ${s.greed}`:'风险累积，本金耗尽');}
function position(s,p){if(s.version!==3&&!features(s).position)return false;let c=s.combat;let floor=c?.faith?c.floor:0;if(c?.locked&&p<s.position){log(s,'继续格局：今天不能减仓。');return false;}let old=s.position;if(s.version===3){if(p<old)p=Math.max(p,s.boughtToday||0);else if(p>old)s.boughtToday=(s.boughtToday||0)+Math.max(0,Math.min(p,150)-old);}s.position=clamp(p,floor,150);if(c&&old!==s.position){c.changes++;if(s.position<old&&has(s,'cup')&&!c.cupUsed){heal(s,4);c.cupUsed=true;}if(c.market==='range'&&c.changes>1)loss(s,2,false,true);if(c.market==='liquidity'&&s.position>old)c.energy=Math.max(0,c.energy-1);}return true;}
export function intent(s,offset=0){if(!s.combat)return null;if(s.version>=3)return offset?null:publicQuote(s);let m=marketFor(s),i=(s.combat.turn-1+offset)%m.sequence.length;return {value:m.sequence[i],mood:features(s).emotion?m.moods[i]:3,phase:m.boss?(i<m.days/3?'人人股神':i<m.days*2/3?'高位震荡':'退潮'):m.name};}
export function hotSector(s){return ['科技','消费','新能源','红利'][(s.combat?.turn||1)%4];}
export function cardCost(s,card){if(s.version===4)return 1;let c=s.combat;let cost=CARD[card.id].cost;if(has(s,'vip')&&c?.playedTotal===0)cost--;if(card.id==='add'&&s.statuses.fomo)cost=0;return Math.max(0,cost);}
function draw(s,n){let c=s.combat;for(let i=0;i<n;i++){if(!c.draw.length){c.draw=shuffle(s,c.discard);c.discard=[];}if(!c.draw.length)break;if(c.hand.length>=10)break;c.hand.push(c.draw.pop());}}

function unlock(s){if(![2,3,4].includes(s.version))return;const target=stage(s);while(s.unlockedStage<target){s.unlockedStage++;const milestone=STAGES[s.unlockedStage];for(const id of [...milestone.cards,...(s.version===4&&s.unlockedStage===2?['annuity']:s.version===4&&s.unlockedStage===3?['retain']:[])]){const card={id,uid:s.uid++,up:false};s.deck.push(card);if(s.combat)s.combat.draw.push(card);}log(s,`新解锁：${milestone.title} · 每回合抽 ${milestone.hand} 张牌`);}}

function startDay(s){let c=s.combat;if(s.version===4){startManualTape(s);startBookDay(s);}else if(s.version===3){s.boughtToday=0;c.dayLedger=[];startTape(s);}unlock(s);c.energy=features(s).energy-(c.turn===1&&s.statuses.dependency?1:0);c.changes=0;c.played=0;c.todayGain=0;c.startHp=s.hp;c.boost=1;c.helmetUsed=false;c.locked=false;c.defer=false;c.keepBlock=false;c.held=false;c.rumorSignal=rand(s)>.5?'上涨':'下跌';c.mood=intent(s).mood;draw(s,features(s).hand-(s.statuses.regret?1:0)+(s.version===4?((has(s,'vip')&&c.turn===1?1:0)+(has(s,'book')&&c.stable>=2?1:0)+(s.statuses.extraDraw||0)-(s.statuses.dependency&&c.turn===1?1:0)):0));if(s.version===4)delete s.statuses.extraDraw;if([2,3,4].includes(s.version)&&s.rounds===0){const desired=['probe','reduce'];const pool=[...c.hand,...c.draw];c.hand=desired.map(id=>pool.splice(pool.findIndex(x=>x.id===id),1)[0]);c.draw=pool;}if(s.statuses.regret){s.statuses.regret--;if(!s.statuses.regret)delete s.statuses.regret;}if(s.version!==4&&s.statuses.fomo&&intent(s).value>0){position(s,s.position+10);log(s,'FOMO：看见上涨，自动增加 10% 仓位。');}if(s.statuses.mouth&&s.version!==4){loss(s,2,false,true);log(s,'嘴硬：每日支出 ¥2,000。');}if(s.version===4){triggerOpening(s,{draw,log});syncBook(s);}}
function enter(s,node){if(s.screen!=='map'||!s.map[s.layer]?.some(n=>n.id===node.id))throw Error('该节点尚不可进入');s.node=node;s.path.push(node.id);if(['market','elite','boss'].includes(node.type)){s.screen='battle';s.combat={market:node.market,turn:1,alpha:0,energy:3,block:0,draw:shuffle(s,s.deck),discard:[],hand:[],played:0,playedTotal:0,chain:0,stable:0,changes:0,boost:1,dividend:0,inverse:has(s,'reverse'),debts:[],tape:[3,-4,5,2,-3,6,-2,4,3,-5,2,4,-1,3],rumorBet:null,rumorTruth:rand(s)>.5};startDay(s);log(s,s.version>=3?'开盘。未来走势未知，点击按钮推进时间。':`进入行情：${marketFor(s).name}`);}else{s.screen=node.type;if(node.type==='shop'){s.shop={cards:s.version===4?offerCards(()=>rand(s),4,{elite:true}):shuffle(s,CARDS.filter(c=>!c.new&&(!STARTER.includes(c.id)||([2,3].includes(s.version)&&!s.deck.some(d=>d.id===c.id))))).slice(0,4).map(c=>c.id),relic:shuffle(s,RELICS.filter(r=>!has(s,r.id)))[0]?.id,bought:[],removed:false};}}}
function play(s,index){let c=s.combat;if(s.screen!=='battle'||!Number.isInteger(index)||!c.hand[index])throw Error('请选择手牌');if(s.version===4)return playTrading(s,index,{draw,log});let card=c.hand[index],d=CARD[card.id],cost=cardCost(s,card);const restriction=tradingRestriction(s,card);if(restriction)throw Error(restriction);c.currentCard=card.id;if(c.energy<cost)throw Error('交易点不足');if((c.locked||c.faith)&&['reduce','stop','empty','cashout'].includes(card.id))throw Error(c.faith?'龙头信仰已锁仓，本场不能主动减仓':'继续格局：本回合不能减仓');c.energy-=cost;c.hand.splice(index,1);c.played++;c.playedTotal++;s.used[card.id]=(s.used[card.id]||0)+1;let up=intent(s).value>0;if(c.inverse)up=!up;let bonus=card.up?1.35:1;let g=n=>gain(s,n*bonus,false,d.type,d.sector),b=n=>{const amount=Math.round(n*bonus);c.block+=amount;if(s.version===3){const fee=Math.round(amount*.05*1000)/1000;loss(s,fee,false,true);}};log(s,`打出「${d.name}${card.up?'+':''}」`);
switch(card.id){
case'probe':position(s,Math.min(100,s.position+10));g(5);if(s.version===3)c.boost*=1.3;break;
case'add':position(s,s.version===3?Math.min(100,s.position+(s.statuses.fomo?40:20)):s.position+(s.statuses.fomo?40:20));delete s.statuses.fomo;if(s.version===3)g(6);else c.boost*=1.3;break;
case'reduce':position(s,s.position-20);b(8);break;
case'watch':draw(s,1);b(2);break;
case'stop':position(s,s.position-20);s.statuses={};break;
case'profit':if(s.lastProfit)g(10);s.greed=Math.max(0,s.greed-2);break;
case'bottom':g(c.mood===5?0:c.mood===0?18:s.lastDown?12:5);break;
case'chase':if(c.mood===0)loss(s,5,false,true);else g(c.mood>=4?14:7);break;
case'allin':position(s,Math.max(s.position,100));c.boost*=2;c.doubleRisk=true;break;
case'empty':position(s,0);b(15);break;
case'break':g(up?18:9);break;
case'volume':draw(s,2);position(s,s.position+10);c.energy++;break;
case'confirm':g(8);if(up)c.boost*=2;break;
case'faith':c.faith=true;c.floor=s.position;break;
case'hold':c.locked=true;c.held=true;break;
case'left':g(6+Math.max(0,3-c.mood)*4);break;
case'dip':position(s,s.position+20);g(up?6:18);break;
case'panic':b(10);if(c.mood<=1)draw(s,2);break;
case'gold':g(c.mood<=1?28:12);if(c.mood<=1)heal(s,6);break;
case'bank':g(5);b(7);break;
case'coal':g(7);b(5);break;
case'dividend':c.dividend+=Math.round(4*bonus);break;
case'cash':b(12);if(s.position<=50)heal(s,4);break;
case'value':g(Math.min(c.block,30));c.keepBlock=true;break;
case'limit':if(up){g(10+c.chain*5);c.chain++;}else{loss(s,8+c.chain*5,false,true);c.chain=0;log(s,'炸板！别把运气当成实力。');}break;
case'leverage':position(s,s.position+30);s.greed=Math.min(5,s.greed+1);break;
case'inverse':c.inverse=!c.inverse;b(6);break;
case'contrary':g(up?4:20);break;
case'cashout':gain(s,s.greed*5*bonus,true);s.greed=0;position(s,s.position-20);break;
case'ignore':c.defer=true;break;
}
c.discard.push(card);
if(d.type==='红利'&&has(s,'abacus'))b(3);if(c.market==='earnings'&&d.type!=='红利'&&!['基础'].includes(d.type))loss(s,1,false,true);if(c.market==='quant'&&c.played>4)loss(s,6,false,true);delete c.currentCard;record(s);}
function endDay(s){if(s.screen!=='battle')throw Error('当前不在交易中');let c=s.combat,m=marketFor(s),v=intent(s).value;c.tape??=[];c.tape.push(v);log(s,s.version===4?`第 ${c.turn} 日收盘 · 指数 ¥${c.live.price.toFixed(2)} · ${v.toFixed(2)}%`:`第 ${c.turn} 日收盘 · 基础行情 ¥${Math.round(Math.abs(v)*1000)}`);
if(s.version===4){settleTrading(s);if(s.hp<=0){finish(s,false,'账户资产耗尽');return;}}else if(v>0){gain(s,v);if(s.position===0&&features(s).greed){s.statuses.fomo=1;s.statuses.regret=3;log(s,'踏空：获得 FOMO；未来 3 回合少抽 1 张牌。');}}else loss(s,-v,true);if(s.screen==='result')return;
if(s.version!==4&&c.held){if(v>0)gain(s,26);else{s.statuses.mouth=1;log(s,'继续格局失败：获得嘴硬（每日亏损 2）。');}}
if(s.version!==4&&c.dividend){c.ledgerLabel='现金分红';gain(s,c.dividend,true);delete c.ledgerLabel;}if(s.version!==4&&c.market==='rumor'&&c.turn===3&&c.rumorBet!==null){if(c.rumorBet===c.rumorTruth)gain(s,14,true);else loss(s,12,false,true);log(s,`小作文${c.rumorTruth?'属实':'被辟谣'}，你的判断${c.rumorBet===c.rumorTruth?'正确':'错误'}。`);}
for(let debt of c.debts.filter(x=>x.due<=c.turn))loss(s,debt.amount,false,true);c.debts=c.debts.filter(x=>x.due>c.turn);if(s.screen==='result')return;
s.lastProfit=s.hp>c.startHp;s.lastDown=v<0;if(features(s).greed&&s.lastProfit)s.greed=Math.min(5,s.greed+1);else if(features(s).greed&&v<0)s.greed=Math.max(0,s.greed-1);c.stable=c.changes===0?c.stable+1:0;s.rounds++;s.history.push(s.hp);record(s);
if(m.training&&c.turn>=m.days){unlock(s);s.screen='build';s.coins=60;addRelic(s,'cup');log(s,'全部系统已开放。选择你的第一套构筑。');return;}
if(c.turn>=m.days&&s.version===4&&c.playedTotal===0){finish(s,false,'本段行情没有参与任何交易');return;}
if(c.turn>=m.days&&c.alpha<m.minAlpha){finish(s,false,`错过行情：累计策略收益 ¥${Math.round(c.alpha*1000)} / ¥${m.minAlpha*1000}，未达到最低收益目标`);return;}
let won=c.turn>=m.days||(s.version!==4&&!m.boss&&!m.training&&c.turn>=2&&c.alpha>=m.goal);if(won){for(let debt of c.debts)loss(s,debt.amount,false,true);c.debts=[];if(s.screen==='result')return;if(m.boss){finish(s,true,'穿越牛熊，平安收盘');return;}s.screen='reward';s.coins+=m.elite?45:25;s.reward={cards:s.version===4?offerCards(()=>rand(s),3,{elite:!!m.elite}):shuffle(s,CARDS.filter(x=>!x.new&&(!STARTER.includes(x.id)||([2,3].includes(s.version)&&!s.deck.some(d=>d.id===x.id))))).slice(0,3).map(x=>x.id),relic:m.elite?shuffle(s,RELICS.filter(x=>!has(s,x.id)))[0]?.id:null};if(s.reward.relic)addRelic(s,s.reward.relic);log(s,'行情结束。复利属于还留在牌桌上的人。');return;}
if(s.version!==4||!c.retained){c.discard.push(...c.hand);c.hand=[];}if(!c.keepBlock)c.block=0;c.turn++;startDay(s);}
function finish(s,won,cause){s.screen='result';s.won=won;s.cause=cause;record(s);log(s,won?'恭喜，你比疯牛活得更久。':'你曾经赚到过。');}
function addCard(s,id){s.deck.push({id,uid:s.uid++,up:false});log(s,`加入卡组：${CARD[id].name}`);}
function addRelic(s,id){if(has(s,id)){heal(s,8);return;}s.relics.push(id);if(id==='old')heal(s,20);log(s,`获得习惯：${RELICS.find(r=>r.id===id).name}`);}
function advance(s,skip=0){s.layer=Math.min(s.map.length-1,s.layer+1+skip);s.screen='map';s.combat=null;delete s.node;}
function event(s,choice){let e=EVENTS[s.node.event];if(![0,1].includes(choice))throw Error('无效的事件选项');let first=choice===0,skip=0;switch(e.id){case'colleague':if(first){addCard(s,shuffle(s,['break','hold','confirm'])[0]);s.statuses.fomo=1;}else s.coins+=25;break;case'guru':if(first){addCard(s,'break');s.statuses.dependency=1;}else{heal(s,8);s.greed=Math.max(0,s.greed-1);}break;case'delete':if(first){heal(s,20);skip=1;}else addCard(s,'ignore');break;case'dad':if(first){addCard(s,'bank');s.coins+=15;}else{addCard(s,'leverage');addCard(s,'limit');}break;case'tea':if(first)addRelic(s,'cup');else{s.coins+=40;s.greed=Math.min(5,s.greed+1);}break;case'fomo':if(first){s.statuses={};s.greed=0;}else{addCard(s,'faith');if(s.version===4)s.statuses.extraDraw=1;else position(s,s.position+20);}break;}advance(s,skip);}
export function act(state,action){let s=structuredClone(state);if(!features(s).full&&['enter','buy','remove','rest','upgrade','event','leave','tool','bet'].includes(action.type))throw Error('完成开盘练习后开放此操作');switch(action.type){
case'build':{if(s.screen!=='build'||s.build)throw Error('当前不能选择流派');const b=BUILDS.find(x=>x.id===action.id);if(!b)throw Error('无效的流派');for(const id of s.version===4?(b.expandedCards||b.cards):b.cards)addCard(s,id);s.build=b.id;advance(s);break;}
case'enter':{let n=s.map[s.layer]?.find(n=>n.id===action.id);if(!n)throw Error('无效节点');enter(s,n);break;}
case'play':play(s,action.index);break;
case'advance':{if(s.version!==4||s.screen!=='battle'||s.combat.live.step===5)throw Error('当前不能推进时间');const target=slots(s).find(k=>k>s.combat.live.step)??5;advanceTape(s,target);syncBook(s);log(s,target===5?'15:00 已收盘，查看今日结算。':'进入 '+publicQuote(s).time+'，本时段可出一张牌。');break;}
case'tick':if(s.version!==3||s.screen!=='battle')throw Error('当前不能推进行情');tickTape(s);break;
case'end':{if(s.version>=3&&(!s.combat?.live||s.combat.live.step<(s.version===4?5:6)))throw Error('今日尚未收盘，请推进至 15:00');const c=s.combat,opening=c?.startHp,rows=c?.dayLedger,day=s.rounds+1;endDay(s);if(s.version>=3)s.lastSettlement={day,opening:Math.round(opening*1000),rows:[...rows],closing:Math.round(opening*1000)+rows.reduce((a,r)=>a+r.amount,0)};break;}
case'bet':if(s.screen!=='battle'||s.combat.market!=='rumor'||s.combat.turn!==1||s.combat.rumorBet!==null||typeof action.value!=='boolean')throw Error('当前无法选择消息判断');s.combat.rumorBet=action.value;log(s,'你的判断已记录，第 3 日公布结果。');break;
case'reward':if(s.screen!=='reward'||(action.id&&!s.reward.cards.includes(action.id)))throw Error('无效奖励');if(action.id)addCard(s,action.id);advance(s);break;
case'event':if(s.screen!=='event')throw Error('没有待处理事件');event(s,action.index);break;
case'leave':if(!['shop','rest'].includes(s.screen))throw Error('当前无法离开');advance(s);break;
case'buy':{if(s.screen!=='shop')throw Error('当前不在商店');let relic=action.kind==='relic',price=relic?65:s.version===4?cardPrice(action.id):35,key=(relic?'r:':'c:')+action.id;if(s.shop.bought.includes(key)||s.coins<price||(relic?s.shop.relic!==action.id:!s.shop.cards.includes(action.id)))throw Error('无法购买');s.coins-=price;s.shop.bought.push(key);relic?addRelic(s,action.id):addCard(s,action.id);break;}
case'remove':{if(s.screen!=='shop'||s.shop.removed||s.coins<30||s.deck.length<=5)throw Error('无法删牌');let index=s.deck.findIndex(c=>c.uid===action.uid);if(index<0||(has(s,'old')&&STARTER.includes(s.deck[index].id)))throw Error('祖传账户保护初始卡牌');s.deck.splice(index,1);s.coins-=30;s.shop.removed=true;log(s,'放下执念，精简卡组。');break;}
case'rest':if(s.screen!=='rest')throw Error('当前不在复盘室');heal(s,24);s.greed=Math.max(0,s.greed-2);advance(s);break;
case'upgrade':{if(s.screen!=='rest')throw Error('当前不在复盘室');let card=s.deck.find(c=>c.uid===action.uid);if(!card||card.up||!(s.version===4?canUpgrade(card.id):UPGRADABLE.includes(card.id)))throw Error('请选择可升级的数值策略牌');card.up=true;log(s,`${CARD[card.id].name}+：已升级，具体效果见牌面。`);advance(s);break;}
case'tool':{if(s.screen!=='battle'||s.toolUsed)throw Error('临时停牌每轮生涯只能使用一次');s.toolUsed=true;if(s.version===4){if(s.combat.live.step===5)throw Error('收盘后不能买入对冲');s.combat.block+=10;s.combat.pending.push({label:'应急对冲成本',amount:-500,formula:'额度 ¥10,000 × 5%'});log(s,'应急对冲已配置，收盘扣除 ¥500。');}else if(s.version===3){s.combat.block+=30;loss(s,1.5,false,true);log(s,'应急对冲：支付 ¥1,500，新增 ¥30,000 对冲额度。');}else{s.combat.block+=1000;log(s,'临时停牌：本次收盘获得 1000 风控。');}break;}
case'abandon':finish(s,false,'主动离场，保住了自己的睡眠');break;
default:throw Error('未知操作');}record(s);return s;}
export function validRun(s){if(s?.version===4&&(!s.book||!Number.isFinite(s.book.cash)||!Number.isFinite(s.book.equity)||!(s.book.lastPrice>0)||!Array.isArray(s.book.lots)||s.book.lots.some(l=>!Number.isFinite(l.units)||l.units<0||!(l.cost>0)||!(l.basis>0)||!Number.isInteger(l.day))))return false;return [1,2,3,4].includes(s?.version)&&Array.isArray(s.deck)&&s.deck.length>=4&&s.deck.every(c=>CARD[c.id]&&Number.isFinite(c.uid))&&Array.isArray(s.map)&&s.map.length===(s.version===1||s.legacyRoute?9:7)&&Number.isInteger(s.layer)&&s.layer>=0&&s.layer<s.map.length&&Number.isFinite(s.hp)&&s.hp>=0&&Number.isFinite(s.position)&&s.position>=0&&s.position<=(s.version===4?10000:150)&&Number.isInteger(s.greed)&&s.greed>=0&&s.greed<=5&&['map','battle','reward','event','shop','rest','result','build'].includes(s.screen)&&(!['battle','reward'].includes(s.screen)||(s.combat&&(s.combat.market==='training'||MARKETS.some(m=>m.id===s.combat.market))&&Array.isArray(s.combat.hand)));}
